### ISSUE TITLE
Dodać drukowanie raportów do pdfa

### ISSUE THREAD

**Issue by magdzikk** [zhr/ziher#102]

**Comment by magdzikk** [comment]
@perk czy mógłbyś mi wygenerować ze starego systemu po jednym pdfie dla każdego typu sprawozdania? Finansowe, finansowe 1% itd? Z góry dzięki :)

**Comment by magdzikk** [comment]
Zostało do zrobienia:

- tworzenie tekstów do ramek w kontrolerze, a nie w widoku
- dodanie "zł" przy kwotach

**Comment by magdzikk** [comment]
https://github.com/zhr/ziher/pull/112

**Comment by perk** [comment]
Zrobione.
