### ISSUE TITLE
Pozwolić administratorowi na tworzenie książki w przeszłości

### ISSUE THREAD

**Issue by perk** [zhr/ziher#69]
Administrator powinien móc stworzyć książkę w przeszłości, m.in. po to, żeby móc wpisać dla nowe jednostki saldo początkowe do zablokowania.

Wystarczy pozwolić administratorowi na tworzenie książek w tym lub poprzednim roku.

**Comment by mazowsze** [comment]
Czy to znaczy, że superadmin, może wpisać nową książkę do zamkniętego roku?
Widzę tutaj sprzeczność w momencie, jeśli mamy zrobiony bilans i na danych z ZiHERa został on opracowany.

**Comment by perk** [comment]
Tak, może - w tym momencie można dowolnie otwierać i zamykać książki.
Nie ma w nim jeszcze takiego pojęcia jak "zamknięty rok" - jest tylko zbiór książek, które mogą być w danym roku dowolnie otwarte / zamknięte.

Pomysł na to jest taki, żeby dać superadminowi narzędzie do blokowania zbilansowanych już wpisów - tzn. ustawiamy datę rozgraniczającą część zablokowaną od odblokowanej.
Oczywiście z historią kto i jak tę blokadę zmieniał.

Np. jeżeli ustawimy blokadę na 1 stycznia 2016 to nic wcześniej nie może zostać dodane - żadne wpisy do książek finansowych czy inwentarzowej.

Chcemy tak zrobić, ponieważ często mamy sytuację, gdy rok już niby jest zbilansowany, a my otwieramy jakąś książkę po 9 miesiącach - bo okazuje się, że był jednak błąd.

Będziemy to realizować tutaj: https://github.com/zhr/ziher/issues/28

**Comment by mazowsze** [comment]
Ok.
