### ISSUE TITLE
Przy ujemnej sumie książki nie sprawdzać czy 1% jest od niej mniejszy

### ISSUE THREAD

**Issue by magdzikk** [zhr/ziher#93]
Taka sytuacja nie ma sensu: <img width="1151" alt="image" src="https://user-images.githubusercontent.com/1413543/28137799-d33af616-674e-11e7-9fd2-b6f3cc7e26ea.png">

**Comment by perk** [comment]
Poprawione tu: https://github.com/zhr/ziher/issues/114
